# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 188edd90a2224eab7f4250809e14729fdc4641b9664c439bbab03f67c87510d5967204d9c4d0586a8e4b6300c5cd51d37be1eb578f042088acaa4393ff8772c0

test:
  secret_key_base: 7be2d8269075000523b5a7f724866ca4f7800e81e394991b95ad5074ba811f5a2aaa3ed166f2fe44fcaa40a24ccdb5b84f2f1507188a5dde63fe2446d6766363

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
